# This file is part of the Ocrend Framewok 2 package.
#
# (c) Ocrend Software <info@ocrend.com>
#
# For the full copyright and license information, please view the LICENS
# file that was distributed with this source code.

# Conexión con la base de datos principal
database:
  host: localhost
  user: root
  pass: 
  name: ocrend
  port: 1521
  protocol: TCP
  motor: mysql
  
# Configuración de servidor SMTP
mailer:
  host: 
  user: 
  pass: 
  port: 587
  logo: https://ocrend.com/views/app/images/logo.png

# Configuración de sesiones
sessions:
  unique: 0CR3ND2017
  life_time: 3600 

# Variables del framework
framework:
  debug: false
  version: 2.0.5

# Configuración del sitio
site:
  name: Ocrend Framework 2
  author: Brayan Narváez
  author_email: prinick@ocrend.com
  timezone: America/Caracas
  url: http://localhost/Ocrend-Framework/
  router:
    path: localhost/Ocrend-Framework/
    protocol: http
